platform :ios, '16.0'

target 'Todoey-UIKit-iOS16' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Todoey-UIKit-iOS16
  
  pod 'RealmSwift', '~>10.39.0'

end